# Generated by Django 4.1.3 on 2023-01-17 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Medicio", "0003_d"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="b",
            name="a",
        ),
        migrations.RemoveField(
            model_name="c",
            name="a",
        ),
        migrations.RemoveField(
            model_name="d",
            name="a",
        ),
        migrations.DeleteModel(
            name="A",
        ),
        migrations.DeleteModel(
            name="B",
        ),
        migrations.DeleteModel(
            name="C",
        ),
        migrations.DeleteModel(
            name="D",
        ),
    ]
