# Generated by Django 4.1.3 on 2023-01-17 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Medicio", "0005_customer_person_employee_customerb_customera_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Publication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("headline", models.CharField(max_length=100)),
                ("publication", models.ManyToManyField(to="Medicio.publication")),
            ],
        ),
    ]
