# Generated by Django 4.1.3 on 2023-02-04 11:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("Medicio", "0007_patientmedication_remove_customer_person_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="patientmedication",
            name="updated_by",
        ),
        migrations.AddField(
            model_name="patientmedication",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="patientmedication",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
