# Generated by Django 4.1.3 on 2023-02-04 12:16

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("Medicio", "0008_remove_patientmedication_updated_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="patientmedication",
            name="status",
            field=models.BooleanField(default=False, verbose_name="الحالة"),
        ),
        migrations.AlterField(
            model_name="patientmedication",
            name="medication",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="Medicio.medication",
                verbose_name="الدواء",
            ),
        ),
        migrations.AlterField(
            model_name="patientmedication",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="Medicio.patient",
                verbose_name="المريض",
            ),
        ),
        migrations.AlterField(
            model_name="patientmedication",
            name="user",
            field=models.ForeignKey(
                default=django.contrib.auth.models.User,
                editable=False,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
