# Generated by Django 4.1.3 on 2023-02-04 12:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("Medicio", "0009_patientmedication_status_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="medication",
            name="description",
        ),
        migrations.RemoveField(
            model_name="patientmedication",
            name="created_at",
        ),
        migrations.AddField(
            model_name="patientmedication",
            name="updated_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="تاريخ التحديث",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="medication",
            name="commercial_name",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="الاسم التجاري"
            ),
        ),
        migrations.AlterField(
            model_name="medication",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="تاريخ النهاية"),
        ),
        migrations.AlterField(
            model_name="medication",
            name="dosage",
            field=models.TextField(
                blank=True, max_length=100, null=True, verbose_name="الاستخدام"
            ),
        ),
        migrations.AlterField(
            model_name="medication",
            name="duration",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="الفترة"
            ),
        ),
        migrations.AlterField(
            model_name="medication",
            name="end_date",
            field=models.DateField(
                blank=True, max_length=100, null=True, verbose_name="تاريخ النهاية"
            ),
        ),
        migrations.AlterField(
            model_name="medication",
            name="frequency",
            field=models.CharField(
                blank=True,
                choices=[
                    ("OD", "مرة باليوم"),
                    ("BDS", "مرتين باليوم"),
                    ("T.I.D.", "ثلاث مرات باليوم"),
                    ("Q.I.D.", "أربعة مرات في اليوم"),
                    ("Q.Q.H.", "كل أربع ساعات"),
                    ("EOD", "مرة كل يومين"),
                    ("Q.N.", "كل ليلة"),
                    ("Q.H.S.", "عند النوم"),
                    ("Q.H.", "كل ساعة"),
                    ("P.R.N.", "وقت الحاجة"),
                ],
                max_length=10,
                null=True,
                verbose_name="التكرار",
            ),
        ),
        migrations.AlterField(
            model_name="medication",
            name="patients",
            field=models.ManyToManyField(
                through="Medicio.PatientMedication",
                to="Medicio.patient",
                verbose_name="المريض",
            ),
        ),
        migrations.AlterField(
            model_name="medication",
            name="scientific_name",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="الاسم العلمي"
            ),
        ),
        migrations.AlterField(
            model_name="medication",
            name="start_date",
            field=models.DateField(
                blank=True, max_length=100, null=True, verbose_name="تاريخ البداية"
            ),
        ),
    ]
