# Generated by Django 4.1.3 on 2023-02-04 14:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("Medicio", "0010_remove_medication_description_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="medication",
            options={"verbose_name": "الأدوية", "verbose_name_plural": "الأدوية"},
        ),
        migrations.AlterModelOptions(
            name="patient",
            options={"verbose_name": "المريض", "verbose_name_plural": "المرضى"},
        ),
        migrations.AlterModelOptions(
            name="patientmedication",
            options={"verbose_name": "الاستخدام", "verbose_name_plural": "الاستخدامات"},
        ),
        migrations.AlterField(
            model_name="patient",
            name="address",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="العنوان"
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="allergy",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="حساسية من"
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="blood_types",
            field=models.CharField(
                blank=True, max_length=3, null=True, verbose_name="فصيلة الدم"
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="city",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="المدينة"
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="country",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="الدولة"
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="تاريخ الإنشاء"),
        ),
        migrations.AlterField(
            model_name="patient",
            name="dob",
            field=models.DateField(blank=True, null=True, verbose_name="تاريخ الميلاد"),
        ),
        migrations.AlterField(
            model_name="patient",
            name="height",
            field=models.FloatField(
                blank=True, max_length=100, null=True, verbose_name="الطول"
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="name",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="الاسم"
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="phone",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="رقم الهاتف"
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="weight",
            field=models.FloatField(
                blank=True, max_length=100, null=True, verbose_name="الوزن"
            ),
        ),
        migrations.AlterField(
            model_name="patientmedication",
            name="user",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
