# Generated by Django 4.1.3 on 2023-02-04 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Medicio", "0014_alter_patientmedication_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="medication",
            name="medicine_type",
            field=models.CharField(
                choices=[("tablets", "حبوب"), ("injection", "حُقن"), ("syrup", "شراب")],
                default="tablets",
                max_length=15,
                verbose_name="نوع الدواء",
            ),
        ),
        migrations.AddField(
            model_name="medication",
            name="quantity",
            field=models.PositiveIntegerField(default=1, verbose_name="العبوة"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="patientmedication",
            name="status",
            field=models.CharField(
                choices=[("0", "ليس بعد"), ("1", "تم تناوله")],
                default="0",
                max_length=1,
                verbose_name="الحالة",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="patientmedication",
            unique_together={("patient", "medication")},
        ),
    ]
