# Generated by Django 4.1.3 on 2023-02-04 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Medicio", "0015_medication_medicine_type_medication_quantity_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="patientmedication",
            unique_together=set(),
        ),
    ]
