# Generated by Django 4.1.3 on 2023-02-04 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Medicio", "0016_alter_patientmedication_unique_together"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="medication",
            name="medicine_type",
        ),
        migrations.RemoveField(
            model_name="medication",
            name="quantity",
        ),
    ]
