# Generated by Django 4.1.3 on 2023-02-04 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Medicio", "0017_remove_medication_medicine_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="medication",
            name="medicine_type",
            field=models.CharField(
                choices=[("tablets", "حبوب"), ("injection", "حُقن"), ("syrup", "شراب")],
                default="tablets",
                max_length=15,
                verbose_name="نوع الدواء",
            ),
        ),
        migrations.AddField(
            model_name="medication",
            name="quantity",
            field=models.PositiveIntegerField(default=1, verbose_name="العبوة"),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="patientmedication",
            unique_together={("patient", "medication")},
        ),
    ]
