# Generated by Django 4.1.3 on 2023-02-04 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Medicio", "0018_medication_medicine_type_medication_quantity_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="medication",
            old_name="dosage",
            new_name="usage",
        ),
        migrations.AddField(
            model_name="medication",
            name="dose",
            field=models.FloatField(blank=True, null=True, verbose_name="الجرعة"),
        ),
        migrations.AlterField(
            model_name="patient",
            name="blood_types",
            field=models.CharField(
                blank=True,
                choices=[
                    ("AB+", "AB+"),
                    ("AB-", "AB-"),
                    ("A+", "A+"),
                    ("A-", "A-"),
                    ("B+", "B+"),
                    ("B-", "B-"),
                    ("O+", "O+"),
                    ("O-", "O-"),
                ],
                max_length=3,
                null=True,
                verbose_name="فصيلة الدم",
            ),
        ),
    ]
