# Generated by Django 4.1.3 on 2023-02-04 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Medicio", "0019_rename_dosage_medication_usage_medication_dose_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="medication",
            name="dose",
            field=models.FloatField(default=1, verbose_name="الجرعة"),
            preserve_default=False,
        ),
    ]
