# Generated by Django 4.1.3 on 2023-01-11 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Currency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="اسم العملة")),
                (
                    "type",
                    models.CharField(
                        choices=[("1", "محلي"), ("2", "أجنبي")],
                        max_length=2,
                        verbose_name="نوع العملة",
                    ),
                ),
                ("exchange", models.FloatField(default=0.0, verbose_name="سعر الصرف")),
            ],
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="اسم الموظف")),
                (
                    "max_debit",
                    models.PositiveBigIntegerField(
                        max_length=255, verbose_name="سقف المديونية"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Detail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "account_type",
                    models.CharField(
                        choices=[("1", "عميل"), ("2", "موظف")],
                        max_length=10,
                        verbose_name="نوع الحساب",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="اسم الموظف")),
                (
                    "max_debit",
                    models.PositiveBigIntegerField(
                        max_length=255, verbose_name="سقف المديونية"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Full Name"
                    ),
                ),
                (
                    "dob",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date of birth"
                    ),
                ),
                (
                    "height",
                    models.FloatField(
                        blank=True, max_length=100, null=True, verbose_name="Height"
                    ),
                ),
                (
                    "weight",
                    models.FloatField(
                        blank=True, max_length=100, null=True, verbose_name="weight"
                    ),
                ),
                (
                    "blood_types",
                    models.CharField(
                        blank=True, max_length=3, null=True, verbose_name="Blood Types"
                    ),
                ),
                ("allergy", models.CharField(max_length=255, verbose_name="Allergy")),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Phone"
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Address"
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="city"
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="country"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Note",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.TextField(
                        blank=True, max_length=255, null=True, verbose_name="Title"
                    ),
                ),
                (
                    "body",
                    models.TextField(
                        blank=True, max_length=1000, null=True, verbose_name="Body"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Med_system.patient",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Medication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "scientific_name",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Scientific name",
                    ),
                ),
                (
                    "commercial_name",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Commercial name",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        max_length=1000,
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                (
                    "dosage",
                    models.TextField(
                        blank=True, max_length=100, null=True, verbose_name="dosage"
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("OD", "Once a day"),
                            ("BDS", "Twice daily"),
                            ("T.I.D.", "3 times a day"),
                            ("Q.I.D.", "4 times a day"),
                            ("Q.Q.H.", "Every 4 hours"),
                            ("EOD", "Every other day"),
                            ("Q.N.", "Every night"),
                            ("Q.H.S.", "Every night at bedtime"),
                            ("Q.H.", "Every hour"),
                            ("P.R.N.", "As needed"),
                        ],
                        max_length=10,
                        null=True,
                        verbose_name="frequency",
                    ),
                ),
                (
                    "duration",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="duration"
                    ),
                ),
                (
                    "start_date",
                    models.DateField(
                        blank=True, max_length=100, null=True, verbose_name="start_date"
                    ),
                ),
                (
                    "end_date",
                    models.DateField(
                        blank=True, max_length=100, null=True, verbose_name="end_date"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Med_system.patient",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Master",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.FloatField(verbose_name="المبلغ")),
                (
                    "currency",
                    models.ForeignKey(
                        choices=[("1", "سلف"), ("2", "تسديد سلف")],
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Med_system.currency",
                    ),
                ),
            ],
        ),
    ]
