# Generated by Django 4.1.3 on 2023-01-13 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Med_system", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="max_debit",
            field=models.PositiveBigIntegerField(verbose_name="سقف المديونية"),
        ),
        migrations.AlterField(
            model_name="employee",
            name="max_debit",
            field=models.PositiveBigIntegerField(verbose_name="سقف المديونية"),
        ),
    ]
